name: life_chest
description: A safe container for  your data
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-266.0.dev <4.0.0'

dependencies:
  crypto: ^3.0.2
  encrypt: ^5.0.1
  file_picker: ^5.2.5
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.0.13
  syncfusion_flutter_pdfviewer: ^20.4.54

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - file_settings/
    - logo.png