name: life_chest
description: A safe container for your data
publish_to: 'none'
homepage: https://github.com/theskyblockman/life-chest

version: 1.3.0+10300

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cryptography: ^2.5.0
  cryptography_flutter: ^2.3.0
  file_picker: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.8.3
  path_provider: ^2.0.13
  encrypt: ^5.0.1
  crypto: ^3.0.3
  audio_service: ^0.18.11
  just_audio: ^0.9.32
  mime: ^1.0.4
  test: ^1.24.1
  rxdart: ^0.27.7
  flutter_media_metadata: ^1.0.0+1
  local_auth_crypto: ^1.1.0
  pattern_lock:
    git: https://github.com/theskyblockman/pattern_lock.git
  local_auth: ^2.1.6
  dynamic_color: ^1.6.6
  marquee: ^2.2.3
  flutter_pdfview: ^1.3.1
  package_info_plus: ^4.1.0
  document_file_save_plus: ^2.0.0
  flutter_secure_storage: ^8.0.0
  flutter_video_info: ^1.3.1
  video_player: ^2.7.0
  chewie: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  intl_utils: any
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - file_settings/
    - logo.png
flutter_intl:
  enabled: true

flutter_launcher_icons:
  ios: true
  image_path: "logo.png"
  min_sdk_android: 23
  remove_alpha_ios: true