on:
  push:
    branches: [master]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.0"
      FLUTTER_VERSION: "3.10.0"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - run: .flutter/bin/flutter pub get
      - run: .flutter/bin/flutter analyze --no-fatal-infos --no-fatal-warnings
      - run: .flutter/bin/flutter test
